# Generated by Django 3.2.6 on 2021-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0004_alter_certificate_awarded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='awarded_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='tenant_awarded_by_user_id',
            field=models.BigIntegerField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='tenant_event_id',
            field=models.BigIntegerField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='tenant_schema_name',
            field=models.CharField(default=None, null=True, blank=True, max_length=128),
            preserve_default=False,
        ),
    ]
